<?php
/**
 * @namespace
 */
namespace de\imxnet\imxplatformphp\image;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-05-20 at 22:41:49.
 */
class BoxTest extends \de\codenamephp\platform\test\TestCase {

  /**
   * @var Box
   */
  private $sut = null;

  protected function setUp() {
    $this->sut = new Box();
  }

  public function testgetTopRightCorner() {
    $this->sut->setWidth(400)->getTopLeftCorner()->setX(100)->setY(100);

    self::assertEquals(new Point(500, 100), $this->sut->getTopRightCorner());
  }

  public function testgetBottomRightCorner() {
    $this->sut->setWidth(400)->setHeight(200)->getTopLeftCorner()->setX(100)->setY(100);

    self::assertEquals(new Point(500, 300), $this->sut->getBottomRightCorner());
  }

  public function testgetBottomLeftCorner() {
    $this->sut->setHeight(200)->getTopLeftCorner()->setX(100)->setY(100);

    self::assertEquals(new Point(100, 300), $this->sut->getBottomLeftCorner());
  }
}
